[build-options]
  observabilityIncluded = true

  [package]
  authors = ["WSO2 BFSI"]
  description = "A template to generate Open Banking Paymnet Initiation REST service"
  displayName = "BFSI Payment Initiation API"
  distribution = "2201.3.1"
  export=["bfsi_payment_initiation_api", "bfsi_payment_initiation_api.interceptor", "bfsi_payment_initiation_api.model", "bfsi_payment_initiation_api.util", "bfsi_payment_initiation_api.client"]
  template = true
  icon = "icon.png"
  keywords = ["Kind/Sample", "Type/RestApi", "Category/Service", "Internal/http", "Cost/Free", "Vertical/bfsi"]
  name = "bfsi_payment_initiation_api"
  org = "wso2bfsi"
  version = "1.0.0"

